name: Deploy Python Script via Jump Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create app directory on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PEM }}
        proxy_host: ${{ secrets.JUMP_HOST }}
        proxy_username: ubuntu
        proxy_key: ${{ secrets.PEM }}
        script: mkdir -p ~/app

    - name: Copy Python script to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PEM }}
        proxy_host: ${{ secrets.JUMP_HOST }}
        proxy_username: ubuntu
        proxy_key: ${{ secrets.PEM }}
        source: "main.py"
        target: "~/app/"
        overwrite: true
