name: Deploy Python Script to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create app directory on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PEM }}
        script: |
          set -e
          mkdir -p ~/app

    - name: Copy Python script to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PEM }}
        source: "main.py"
        target: "~/app/"
        overwrite: true

    - name: Install Python and run script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PEM }}
        script: |
          set -e
          sudo apt update
          sudo apt install -y python3 python3-pip
          python3 ~/app/main.py
